weights: runs/train/mark10/weights/last.pt
cfg: 0_mark_ocr/yolov7-2c.yaml
data: 0_mark_ocr/custom.yaml
hyp: data/hyp.scratch.p5.yaml
epochs: 500
batch_size: 2
img_size:
- 416
- 416
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 1
project: runs/train
entity: null
name: mark
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: 50
artifact_alias: latest
freeze:
- 0
world_size: 1
global_rank: -1
save_dir: runs\train\mark11
total_batch_size: 2
